dkTlqkf/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("posts/", include("posts.urls")),
    path("users/", include("users.urls")),
]

home/urls.py
from django.urls import path

from . import views

app_name = "home"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
]

posts/urls.py
from django.urls import path

from . import views

app_name = "posts"
urlpatterns = [
    path("", views.PostListView.as_view(), name="list"),
    path("<int:post_id>/", views.detail, name="detail"),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("signin/", LoginView.as_view(template_name="signin.html"), name="signin"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("<int:pk>/", views.UserDetailView.as_view(), name="detail"),
]

posts/models.py
from django.contrib.auth.models import User
from django.db import models


class Post(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.RESTRICT)
    content = models.CharField(max_length=500)
    view_count = models.PositiveIntegerField(blank=True, default=0)
    parent = models.ForeignKey(
        "self",
        on_delete=models.RESTRICT,
        related_name="comments",
        null=True,
        blank=True,
    )

    def __str__(self) -> str:
        return self.content

users/models.py
from django.db import models

# Create your models here.

home/views.py
from django.views import generic


class IndexView(generic.TemplateView):
    template_name = "home_index.html"

posts/views.py
from django.core.handlers.wsgi import WSGIRequest
from django.shortcuts import render
from django.views import generic

from . import models


class PostListView(generic.ListView):
    template_name = "post_list.html"

    def get_queryset(self):
        return models.Post.objects.order_by("-created_at")


def detail(request: WSGIRequest, post_id: int):
    return render(request, "detail.html")

users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.views import generic


class SignUpView(generic.CreateView):
    template_name = "user_signup.html"
    form_class = UserCreationForm
    success_url = "/"


class UserDetailView(generic.DetailView):
    template_name = "user_detail.html"
    model = get_user_model()

dkTlqkf/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}" />
    <title>dkTlqkf</title>
  </head>

  <body>
    {% include "header.html" %}

    <div class="container-lg d-flex justify-content-center p-3" id="content">
      {% load tz %} {% timezone "Asia/Seoul" %} {% block content %}
      <h1>No content</h1>
      {% endblock %} {% endtimezone %}
    </div>
    <script src="{% static 'bootstrap.bundle.min.js' %}"></script>
  </body>
</html>

dkTlqkf/templates/header.html
<nav class="navbar bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home:index' %}">dkTlqkf</a>

    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarText"
      aria-controls="navbarText"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'posts:list' %}">게시판</a>
        </li>

        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            계정
          </a>
          <ul class="dropdown-menu">
            {% if user.is_authenticated %}
            <li>
              <a class="dropdown-item" href="{% url 'users:detail' user.id %}"
                >{{ user.username }}</a
              >
            </li>
            <li>
              <form method="post" action="{% url 'users:logout' %}">
                {% csrf_token %}
                <input class="dropdown-item" type="submit" value="로그아웃" />
              </form>
            </li>

            {% else %}
            <li><a class="dropdown-item" href="{% url 'users:signup' %}">회원가입</a></li>
            <li><a class="dropdown-item" href="{% url 'users:signin' %}">로그인</a></li>
            {% endif %}
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

home/templates/home_index.html
{% extends 'base.html' %} {% block content %}
<div class="row w-100 justify-content-center">
  <div class="col-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">게시판</h5>
        <p class="card-text">마음 속 깊이 묻혀있는 답답한 감정을 익명으로 마음껏 표현하세요!</p>
        <a href="{% url 'posts:list' %}" class="btn btn-primary">이동</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

home/templates/index.html
{% extends 'base.html' %} {% block content %}
<div class="row w-100 justify-content-center">
  <div class="col-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">게시판</h5>
        <p class="card-text">마음 속 깊이 묻혀있는 답답한 감정을 익명으로 마음껏 표현하세요!</p>
        <a href="{% url 'posts:list' %}" class="btn btn-primary">이동</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

posts/templates/detail.html
{% extends "base.html" %} {% block content %}
<h1>detail</h1>
{% endblock %}

posts/templates/home.html
{% extends "base.html" %} {% block content %}
<div class="list-group">
  {% for post in post_list %}
  <a href="{% url 'posts:detail' post.id %}" class="list-group-item list-group-item-action">
    <div class="d-flex justify-content-between align-items-center w-100">
      <div class="d-flex justify-content-start align-items-center w-75">
        <small class="mx-1">{{ post.id }}</small>
        <div class="mx-2 text-truncate">{{ post.content }}</div>
      </div>
      <div class="d-flex justify-content-end align-items-center w-25">
        <small class="mx-1 text-center">{{ post.created_at }}</small>
      </div>
    </div>
  </a>
  {% endfor %}
</div>
{% endblock %}

posts/templates/list.html
{% extends "base.html" %} {% block content %}
<div class="list-group w-100">
  {% for post in post_list %}
  <a href="{% url 'posts:detail' post.id %}" class="list-group-item list-group-item-action">
    <div class="d-flex justify-content-between align-items-center w-100">
      <div class="d-flex justify-content-start align-items-center w-75">
        <small class="mx-1">{{ post.id }}</small>
        <div class="mx-2 text-truncate">{{ post.content }}</div>
      </div>
      <div class="d-flex justify-content-end align-items-center w-25">
        <small class="mx-1 text-center">{{ post.created_at }}</small>
      </div>
    </div>
  </a>
  {% endfor %}
</div>
{% endblock %}

posts/templates/post_detail.html
{% extends "base.html" %} {% block content %}
<h1>Post Detail</h1>
{% endblock %}

posts/templates/post_list.html
{% extends "base.html" %} {% block content %}
<div class="list-group w-100">
  {% for post in post_list %}
  <a href="{% url 'posts:detail' post.id %}" class="list-group-item list-group-item-action">
    <div class="d-flex justify-content-between align-items-center w-100">
      <div class="d-flex justify-content-start align-items-center w-75">
        <small class="mx-1">{{ post.id }}</small>
        <div class="mx-2 text-truncate">{{ post.content }}</div>
      </div>
      <div class="d-flex justify-content-end align-items-center w-25">
        <small class="mx-1 text-center">{{ post.created_at }}</small>
      </div>
    </div>
  </a>
  {% endfor %}
</div>
{% endblock %}

users/templates/form_error.html
{% if form.errors %}
<div class="alert alert-danger">
  {% for field in form %}
  <!-- 필드 오류 -->
  {% if field.errors %}
  <div>
    <strong>{{ field.label }}</strong>
    {{ field.errors }}
  </div>
  {% endif %} {% endfor %}
  <!-- 넌필드 오류 -->
  {% for error in form.non_field_errors %}
  <div>
    <strong>{{ error }}</strong>
  </div>
  {% endfor %}
</div>
{% endif %}

users/templates/signin.html
{% extends "base.html" %} {% block content %}
<form method="post" action="{% url 'users:signin' %}">
  {% csrf_token %} {% include "form_error.html" %}
  <div class="mb-3">
    <label for="username" class="form-label">아이디</label>
    <input
      type="text"
      class="form-control"
      name="username"
      id="username"
      value="{{ form.username.value|default_if_none:'' }}"
    />
  </div>

  <div class="mb-3">
    <label for="password" class="form-label">비밀번호</label>
    <input
      type="password"
      class="form-control"
      name="password"
      id="password"
      value="{{ form.password.value|default_if_none:'' }}"
    />
  </div>

  <button type="submit" class="btn btn-primary">로그인</button>
</form>
{% endblock %}

users/templates/signup.html
{% extends "base.html" %} {% block content %}
<form method="post" action="{% url 'users:signup' %}">
  {% csrf_token %} {% include "form_error.html" %}
  <div class="mb-3">
    <label for="username" class="form-label">아이디</label>
    <input
      type="text"
      class="form-control"
      name="username"
      id="username"
      value="{{ form.username.value|default_if_none:'' }}"
    />
  </div>

  <div class="mb-3">
    <label for="password1" class="form-label">비밀번호</label>
    <input
      type="password"
      class="form-control"
      name="password1"
      id="password1"
      value="{{ form.password1.value|default_if_none:'' }}"
    />
  </div>

  <div class="mb-3">
    <label for="password2" class="form-label">비밀번호 확인</label>
    <input
      type="password"
      class="form-control"
      name="password2"
      id="password2"
      value="{{ form.password2.value|default_if_none:'' }}"
    />
  </div>

  <button type="submit" class="btn btn-primary">회원가입</button>
</form>
{% endblock %}

users/templates/user_detail.html
{% extends "base.html" %} {% block content %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">아이디</th>
      <th scope="col">가입일</th>
      <th scope="col">마지막 로그인</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">{{ object.id }}</th>
      <td>{{ object.username }}</td>
      <td>{{ object.date_joined }}</td>
      <td>{{ object.last_login }}</td>
    </tr>
  </tbody>
</table>
{% endblock %}

users/templates/user_signin.html
{% extends "base.html" %} {% block content %}
<form method="post" action="{% url 'users:signin' %}">
  {% csrf_token %} {% include "form_error.html" %}
  <div class="mb-3">
    <label for="username" class="form-label">아이디</label>
    <input
      type="text"
      class="form-control"
      name="username"
      id="username"
      value="{{ form.username.value|default_if_none:'' }}"
    />
  </div>

  <div class="mb-3">
    <label for="password" class="form-label">비밀번호</label>
    <input
      type="password"
      class="form-control"
      name="password"
      id="password"
      value="{{ form.password.value|default_if_none:'' }}"
    />
  </div>

  <button type="submit" class="btn btn-primary">로그인</button>
</form>
{% endblock %}

users/templates/user_signup.html
{% extends "base.html" %} {% block content %}
<form method="post" action="{% url 'users:signup' %}">
  {% csrf_token %} {% include "form_error.html" %}
  <div class="mb-3">
    <label for="username" class="form-label">아이디</label>
    <input
      type="text"
      class="form-control"
      name="username"
      id="username"
      value="{{ form.username.value|default_if_none:'' }}"
    />
  </div>

  <div class="mb-3">
    <label for="password1" class="form-label">비밀번호</label>
    <input
      type="password"
      class="form-control"
      name="password1"
      id="password1"
      value="{{ form.password1.value|default_if_none:'' }}"
    />
  </div>

  <div class="mb-3">
    <label for="password2" class="form-label">비밀번호 확인</label>
    <input
      type="password"
      class="form-control"
      name="password2"
      id="password2"
      value="{{ form.password2.value|default_if_none:'' }}"
    />
  </div>

  <button type="submit" class="btn btn-primary">회원가입</button>
</form>
{% endblock %}